default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: borges_development

test:
  <<: *default
  database: borges_test

production:
  <<: *default
  database: borges
  username: borges
  password: <%= ENV['BORGES_DATABASE_PASSWORD'] %>
