# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa8e6049106c8367ad114ebe0d83531e6493dc69eae499ae20671af258f25d626c1ff857d51005def9415418e8ad2f5e8c2ae7b9a7bd9e1d6c596c12af5c2a01

test:
  secret_key_base: a0fc3648fb7d07e872ad4d29e9fba00728fca2cd3f5b659065b011d9b09516b0c80b93592b9edaf9e0317f2836c6573add13dcdab0ce22a7c645076c67eec3e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
